services:
  skills-website:
    build: .
    container_name: skills-website
    restart: unless-stopped
    ports:
      - "3456:80"
    networks:
      - services_services

networks:
  services_services:
    external: true
